#name: Gabriel Peixoto de Carvalho,
#permalink: /blog/:year/:month/:day/:title

#site Settings

title: Gabriel Peixoto de Carvalho
description: personal website
email: gaburiero.c@gmail.com
github_username: gaburiero

#build settings
markdown: kramdown
theme: jekyll-theme-hacker
